// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'API Key',
    appId: '1:1022611646356:web:772c18343b33f9374cd181',
    messagingSenderId: '1022611646356',
    projectId: 'projstidd',
    authDomain: 'projstidd.firebaseapp.com',
    storageBucket: 'projstidd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'API key',
    appId: '1:1022611646356:android:11ae8d067c627d2f4cd181',
    messagingSenderId: '1022611646356',
    projectId: 'projstidd',
    storageBucket: 'projstidd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'API key',
    appId: '1:1022611646356:ios:979d4d25f960bd3a4cd181',
    messagingSenderId: '1022611646356',
    projectId: 'projstidd',
    storageBucket: 'projstidd.appspot.com',
    iosBundleId: 'com.example.projectStidd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'API key',
    appId: '1:1022611646356:ios:979d4d25f960bd3a4cd181',
    messagingSenderId: '1022611646356',
    projectId: 'projstidd',
    storageBucket: 'projstidd.appspot.com',
    iosBundleId: 'com.example.projectStidd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'API key',
    appId: '1:1022611646356:web:c43bf5c5fa028ab84cd181',
    messagingSenderId: '1022611646356',
    projectId: 'projstidd',
    authDomain: 'projstidd.firebaseapp.com',
    storageBucket: 'projstidd.appspot.com',
  );
}
